# From Peter Cooper's 'pismo' gem,
# https://github.com/peterc/pismo/blob/master/lib/pismo/internal_attributes.rb
module Loaders
  TITLE_MATCHERS = [
    '#pname a',
    '.entryheader h1',
    '.entry-title a',
    '.post-title a',
    '.post_title a',
    '.posttitle a',
    '.post-header h1',
    '.entry-title',
    '.post-title',
    '.post h1',
    '.post h3 a',
    'a.datitle',
    '.posttitle',
    '.post_title',
    '.pageTitle',
    '#main h1.title',
    '.title h1',
    '.post h2',
    'h2.title',
    '.entry h2 a',
    '.entry h2',
    '.boite_titre a',
    # ['meta[@name="title"]', lambda { |el| el.attr('content') }],
    'h1.headermain',
    'h1.title',
    '.mxb h1',
    '#content h1',
    '#content h2',
    '#content h3',
    'a[@rel="bookmark"]',
    '.products h2',
    '.caption h3',
    '#main h2',
    '#body h1',
    '#wrapper h1',
    '#page h1',
    '.asset-header h1',
    '#body_content h2',
    'title'
  ]
end
